name: chikin_airdrop_pool_client
description: Dart client for Chikin Airdrop Pool (solana)
version: 0.0.1
homepage: chikin.run
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  solana:
    git: https://github.com/ChikinDeveloper/dart-solana-lib

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: